name: lemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^3.0.1
  qr_flutter: ^4.0.0
  image_picker: ^1.1.2
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BlackHanSans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
  assets:
    - assets\images\lemon_logo.png
    - assets\images\lemon_home.png
    - assets\images\lemon_transparente.png
    - assets\images\qrcode.png
    - assets/week_schedule.json

